steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-f'
      - 'exercise_producer/dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA'
      - 'exercise_producer'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=DEFAULT_NAME=${_DEFAULT_NAME}'
      - '--set-secrets=SECRET_VALUE=${_SECRET_NAME}:latest'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA'

substitutions:
  _REGION: europe-north2
  _AR_REPO: ingestion-pipeline
  _IMAGE: exercise-producer
  _SERVICE: exercise-producer
  _DEFAULT_NAME: Student
  _SECRET_NAME: EXERCISE_SECRET

options:
  logging: CLOUD_LOGGING_ONLY
